name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Run Test Suite
    uses: zavestudios/platform-pipelines/.github/workflows/python-test.yml@660aed58a3bf8413f23df0da545650de9b11b7fc
    with:
      python_version: '3.12'
